// Command benchmatrix orchestrates sequential cmd/benchvs runs across
// multiple HyperGnomon build targets (release tags, origin/main, and the
// current workspace) to produce a release A/B comparison matrix. Each trial
// gets a fresh DB directory, unique API/WS ports, an isolated classify seed
// cache directory (when the target binary supports
// --classify-seed-cache-dir), and the full daemon bandwidth — targets are
// never run concurrently. Results land in benchmatrix.jsonl,
// benchmatrix.md (median/p95 summary with deltas versus origin/main), and
// benchmatrix-runs.md under a timestamped output root. See
// cmd/benchmatrix/README.md and the "Release A/B matrix" section of
// DOCS/BENCHMARKS.md for usage and interpretation rules.
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

func main() {
	var cfg Config
	var targetsRaw string
	flag.StringVar(&cfg.Daemon, "daemon", "203.0.113.10:10102", "DERO daemon RPC address")
	flag.IntVar(&cfg.Trials, "trials", 5, "clean sequential trials per target")
	flag.DurationVar(&cfg.ProbeDuration, "probe-duration", 60*time.Second, "API probe duration per trial")
	flag.IntVar(&cfg.ProbeWorkers, "probe-workers", 32, "concurrent API probe workers")
	flag.StringVar(&cfg.ProbePaths, "probe-paths", "/api/getinfo,/api/getstats,/api/getscids", "comma-separated API paths to probe")
	flag.StringVar(&cfg.ReadyLogPattern, "ready-log-pattern", "Classify probe complete", "child-log marker before API probes")
	flag.DurationVar(&cfg.ReadyTimeout, "ready-timeout", 5*time.Minute, "max wait for readiness marker")
	flag.DurationVar(&cfg.TipTimeout, "tip-timeout", 15*time.Minute, "max wait for target to reach tip")
	flag.StringVar(&cfg.RootDir, "out-dir", "", "output/temp root; default is a timestamped directory under the system temp dir")
	flag.IntVar(&cfg.APIPortStart, "api-port-start", 18082, "first API port assigned to trial targets")
	flag.IntVar(&cfg.WSPortStart, "ws-port-start", 19190, "first WS port assigned to trial targets")
	flag.StringVar(&targetsRaw, "targets", "v1.0.0,origin/main,workspace", "comma-separated refs; use workspace for the current checkout")
	flag.BoolVar(&cfg.DryRun, "dry-run", false, "print build/run plan without fetching, building, or running benchmarks")
	flag.Parse()

	if err := run(cfg, targetsRaw); err != nil {
		fmt.Fprintf(os.Stderr, "benchmatrix: %v\n", err)
		os.Exit(1)
	}
}

func run(cfg Config, targetsRaw string) error {
	if cfg.Trials <= 0 {
		return fmt.Errorf("--trials must be positive")
	}
	if cfg.RootDir == "" {
		cfg.RootDir = filepath.Join(os.TempDir(), "hypergnomon-benchmatrix", time.Now().Format("20060102-150405"))
	}
	cfg.JSONOut = filepath.Join(cfg.RootDir, "benchmatrix.jsonl")
	cfg.RunMarkdownOut = filepath.Join(cfg.RootDir, "benchmatrix-runs.md")
	cfg.SummaryOut = filepath.Join(cfg.RootDir, "benchmatrix.md")
	cfg.BenchvsBinary = filepath.Join(cfg.RootDir, "bin", exeName("benchvs"))

	targets, err := parseTargets(targetsRaw)
	if err != nil {
		return err
	}

	if cfg.DryRun {
		targets = assignDryRunPaths(cfg, targets)
		printDryRun(cfg, buildRunSpecs(cfg, targets))
		return nil
	}

	if err := os.MkdirAll(filepath.Join(cfg.RootDir, "bin"), 0o750); err != nil {
		return err
	}
	if err := fetchRemoteRefs(); err != nil {
		return err
	}
	if err := buildBenchvs(cfg); err != nil {
		return err
	}
	targets, err = prepareTargets(cfg, targets)
	if err != nil {
		return err
	}

	specs := buildRunSpecs(cfg, targets)
	for _, spec := range specs {
		fmt.Printf("benchmatrix: running %s trial %d/%d\n", spec.Target.Name, spec.Trial, cfg.Trials)
		if err := runCommand("", cfg.BenchvsBinary, spec.BenchvsArgs...); err != nil {
			return fmt.Errorf("%s trial %d: %w", spec.Target.Name, spec.Trial, err)
		}
	}

	body, err := os.Open(cfg.JSONOut) // #nosec G304 -- report path is generated by this harness.
	if err != nil {
		return err
	}
	records, err := parseJSONLRuns(body)
	_ = body.Close()
	if err != nil {
		return err
	}
	summaries := summarizeRuns(records, "origin/main")
	if err := writeSummaryMarkdown(cfg.SummaryOut, summaries, "origin/main"); err != nil {
		return err
	}
	fmt.Printf("benchmatrix: wrote %s and %s\n", cfg.JSONOut, cfg.SummaryOut)
	return nil
}

func assignDryRunPaths(cfg Config, targets []Target) []Target {
	out := make([]Target, len(targets))
	for i, target := range targets {
		target.BinaryPath = filepath.Join(cfg.RootDir, "bin", exeName("hypergnomon-"+sanitizeName(target.Ref)))
		out[i] = target
	}
	return out
}

func printDryRun(cfg Config, specs []RunSpec) {
	fmt.Printf("benchmatrix dry-run root: %s\n", cfg.RootDir)
	fmt.Printf("benchvs: %s\n", cfg.BenchvsBinary)
	for _, spec := range specs {
		fmt.Printf("%s trial %d: %s %s\n",
			spec.Target.Name,
			spec.Trial,
			cfg.BenchvsBinary,
			strings.Join(spec.BenchvsArgs, " "),
		)
	}
}

func fetchRemoteRefs() error {
	if err := runCommand("", "git", "fetch", "--tags", "--force", "origin"); err != nil {
		return err
	}
	return runCommand("", "git", "fetch", "origin", "main")
}

func buildBenchvs(cfg Config) error {
	return runCommand("", "go", "build", "-o", cfg.BenchvsBinary, "./cmd/benchvs")
}

func prepareTargets(cfg Config, targets []Target) ([]Target, error) {
	out := make([]Target, len(targets))
	for i, target := range targets {
		safeRef := sanitizeName(target.Ref)
		target.BinaryPath = filepath.Join(cfg.RootDir, "bin", exeName("hypergnomon-"+safeRef))
		if target.Workspace {
			if err := runCommand("", "go", "build", "-o", target.BinaryPath, "./cmd/hypergnomon"); err != nil {
				return nil, err
			}
			target.SupportsSeedCacheDir = binarySupportsSeedCacheDir(target.BinaryPath)
			out[i] = target
			continue
		}
		workDir := filepath.Join(cfg.RootDir, "worktrees", safeRef)
		if err := ensureUnderRoot(cfg.RootDir, workDir); err != nil {
			return nil, err
		}
		if err := os.MkdirAll(filepath.Dir(workDir), 0o750); err != nil {
			return nil, err
		}
		_ = runCommand("", "git", "worktree", "remove", "--force", workDir)
		_ = os.RemoveAll(workDir)
		if err := runCommand("", "git", "worktree", "add", "--detach", workDir, target.Ref); err != nil {
			return nil, err
		}
		if err := runCommand(workDir, "go", "build", "-o", target.BinaryPath, "./cmd/hypergnomon"); err != nil {
			return nil, err
		}
		target.WorkDir = workDir
		target.SupportsSeedCacheDir = binarySupportsSeedCacheDir(target.BinaryPath)
		out[i] = target
	}
	return out, nil
}

// binarySupportsSeedCacheDir probes a built target's --help output for the
// --classify-seed-cache-dir flag. Older refs (v1.0.0, pre-seed-cache main)
// reject unknown flags at startup, so the per-trial seed isolation arg can
// only be passed to binaries that understand it.
func binarySupportsSeedCacheDir(binary string) bool {
	cmd := exec.Command(binary, "--help") // #nosec G204 -- probing a binary this harness just built.
	out, _ := cmd.CombinedOutput()        // flag usage exits non-zero; the text is all we need.
	return helpMentionsFlag(string(out), "classify-seed-cache-dir")
}

func helpMentionsFlag(helpOutput, name string) bool {
	return strings.Contains(helpOutput, "-"+name)
}

func ensureUnderRoot(root, path string) error {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return err
	}
	absPath, err := filepath.Abs(path)
	if err != nil {
		return err
	}
	rel, err := filepath.Rel(absRoot, absPath)
	if err != nil {
		return err
	}
	if rel == "." || strings.HasPrefix(rel, "..") {
		return fmt.Errorf("refusing to operate outside root: %s", path)
	}
	return nil
}

func runCommand(dir, name string, args ...string) error {
	cmd := exec.Command(name, args...) // #nosec G204 -- benchmark harness intentionally runs selected local tools.
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func exeName(base string) string {
	if runtime.GOOS == "windows" {
		return base + ".exe"
	}
	return base
}
