package main

import (
	"fmt"
	"os"
	"time"
)

// Result is one benchvs run against one indexer. writeReport
// appends a markdown section per result so two sequential
// invocations (one per indexer) produce a side-by-side document.
type Result struct {
	Name           string
	Binary         string
	Daemon         string
	GoVersion      string
	HostOS         string
	Timestamp      string
	TipReached     bool
	TimeToTip      time.Duration
	ReadyPattern   string
	ReadyReached   bool
	TimeToReady    time.Duration
	DBBytes        int64
	ProbeDuration  time.Duration
	ProbeWorkers   int
	ProbePaths     []string
	Latency        []PathLatency
	ClassifyTiming string
}

// writeReport appends a markdown section describing r to path. On
// first invocation the file is created with a header. Subsequent
// invocations append — the intent is for the operator to run benchvs
// twice (once per indexer) and see both results in one document.
func writeReport(path string, r Result) error {
	newFile := false
	if _, err := os.Stat(path); os.IsNotExist(err) {
		newFile = true
	}
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()

	if newFile {
		fmt.Fprintln(f, "# Head-to-head: HyperGnomon vs civilware/Gnomon")
		fmt.Fprintln(f)
		fmt.Fprintln(f, "Generated by `cmd/benchvs`. Each section is one sequential run against the same daemon.")
		fmt.Fprintln(f, "Running the two indexers concurrently would skew whichever started first via RPC contention.")
		fmt.Fprintln(f)
	}

	fmt.Fprintf(f, "## %s\n\n", r.Name)
	fmt.Fprintf(f, "- Binary: `%s`\n", r.Binary)
	fmt.Fprintf(f, "- Daemon: `%s`\n", r.Daemon)
	fmt.Fprintf(f, "- Host: `%s`, Go: `%s`\n", r.HostOS, r.GoVersion)
	fmt.Fprintf(f, "- Run at: `%s`\n\n", r.Timestamp)

	fmt.Fprintln(f, "### Scan + storage")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "| metric | value |")
	fmt.Fprintln(f, "|---|---|")
	if r.TipReached {
		fmt.Fprintf(f, "| Time-to-tip (FastSync) | %s |\n", r.TimeToTip.Round(100*time.Millisecond))
	} else {
		fmt.Fprintln(f, "| Time-to-tip (FastSync) | **did not reach tip within timeout** |")
	}
	if r.ReadyPattern != "" {
		if r.ReadyReached {
			fmt.Fprintf(f, "| Time-to-ready (%s) | %s |\n", r.ReadyPattern, r.TimeToReady.Round(100*time.Millisecond))
		} else {
			fmt.Fprintf(f, "| Time-to-ready (%s) | **did not reach readiness marker** |\n", r.ReadyPattern)
		}
	}
	fmt.Fprintf(f, "| DB size at measurement | %s |\n", humanBytes(r.DBBytes))
	fmt.Fprintln(f)

	if r.ClassifyTiming != "" {
		fmt.Fprintln(f, "### Classify timing")
		fmt.Fprintln(f)
		fmt.Fprintf(f, "`%s`\n\n", r.ClassifyTiming)
	}

	if len(r.Latency) > 0 {
		fmt.Fprintln(f, "### API latency")
		fmt.Fprintf(f, "\nProbe duration %s, %d concurrent workers.\n\n",
			r.ProbeDuration.Round(time.Second), r.ProbeWorkers)
		fmt.Fprintln(f, "| path | n | err | p50 | p95 | p99 | max |")
		fmt.Fprintln(f, "|---|---:|---:|---:|---:|---:|---:|")
		for _, lat := range r.Latency {
			fmt.Fprintf(f, "| `%s` | %d | %d | %s | %s | %s | %s |\n",
				lat.Path, lat.N, lat.Errors,
				ms(lat.P50), ms(lat.P95), ms(lat.P99), ms(lat.Max))
		}
		fmt.Fprintln(f)
	}

	return nil
}

// humanBytes formats a byte count into a compact human-readable
// string. Stops at GiB — bench DBs in the multi-TB range would be
// a red flag worth surfacing.
func humanBytes(n int64) string {
	const (
		KB = 1 << 10
		MB = 1 << 20
		GB = 1 << 30
	)
	switch {
	case n >= GB:
		return fmt.Sprintf("%.2f GiB (%d bytes)", float64(n)/GB, n)
	case n >= MB:
		return fmt.Sprintf("%.1f MiB (%d bytes)", float64(n)/MB, n)
	case n >= KB:
		return fmt.Sprintf("%.1f KiB (%d bytes)", float64(n)/KB, n)
	default:
		return fmt.Sprintf("%d bytes", n)
	}
}

// ms formats a duration in millisecond precision for table rows.
// Sub-ms values report as "<1ms" rather than 0 so the operator
// doesn't mistake fast-path cache hits for failed measurements.
func ms(d time.Duration) string {
	if d == 0 {
		return "—"
	}
	if d < time.Millisecond {
		return "<1 ms"
	}
	return d.Round(time.Millisecond).String()
}
