package main

import (
	"encoding/json"
	"fmt"
	"os"
	"time"
)

// Result is one benchvs run against one indexer. writeReport
// appends a markdown section per result so two sequential
// invocations (one per indexer) produce a side-by-side document.
type Result struct {
	Name           string
	TargetRef      string
	Trial          int
	Binary         string
	Daemon         string
	GoVersion      string
	HostOS         string
	Timestamp      string
	TipReached     bool
	TimeToTip      time.Duration
	ReadyPattern   string
	ReadyReached   bool
	TimeToReady    time.Duration
	DBBytes        int64
	ProbeDuration  time.Duration
	ProbeWorkers   int
	ProbePaths     []string
	Latency        []PathLatency
	ClassifyTiming string
	LogPath        string
}

// writeReport appends a markdown section describing r to path. On
// first invocation the file is created with a header. Subsequent
// invocations append — the intent is for the operator to run benchvs
// twice (once per indexer) and see both results in one document.
func writeReport(path string, r Result) error {
	newFile := false
	if _, err := os.Stat(path); os.IsNotExist(err) {
		newFile = true
	}
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600) // #nosec G304 -- report path is operator-selected output.
	if err != nil {
		return err
	}
	defer f.Close()

	if newFile {
		fmt.Fprintln(f, "# Head-to-head: HyperGnomon vs civilware/Gnomon")
		fmt.Fprintln(f)
		fmt.Fprintln(f, "Generated by `cmd/benchvs`. Each section is one sequential run against the same daemon.")
		fmt.Fprintln(f, "Running the two indexers concurrently would skew whichever started first via RPC contention.")
		fmt.Fprintln(f)
	}

	fmt.Fprintf(f, "## %s\n\n", r.Name)
	fmt.Fprintf(f, "- Binary: `%s`\n", r.Binary)
	fmt.Fprintf(f, "- Daemon: `%s`\n", r.Daemon)
	fmt.Fprintf(f, "- Host: `%s`, Go: `%s`\n", r.HostOS, r.GoVersion)
	fmt.Fprintf(f, "- Run at: `%s`\n\n", r.Timestamp)

	fmt.Fprintln(f, "### Scan + storage")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "| metric | value |")
	fmt.Fprintln(f, "|---|---|")
	if r.TipReached {
		fmt.Fprintf(f, "| Time-to-tip (FastSync) | %s |\n", r.TimeToTip.Round(100*time.Millisecond))
	} else {
		fmt.Fprintln(f, "| Time-to-tip (FastSync) | **did not reach tip within timeout** |")
	}
	if r.ReadyPattern != "" {
		if r.ReadyReached {
			fmt.Fprintf(f, "| Time-to-ready (%s) | %s |\n", r.ReadyPattern, r.TimeToReady.Round(100*time.Millisecond))
		} else {
			fmt.Fprintf(f, "| Time-to-ready (%s) | **did not reach readiness marker** |\n", r.ReadyPattern)
		}
	}
	fmt.Fprintf(f, "| DB size at measurement | %s |\n", humanBytes(r.DBBytes))
	fmt.Fprintln(f)

	if r.ClassifyTiming != "" {
		fmt.Fprintln(f, "### Classify timing")
		fmt.Fprintln(f)
		fmt.Fprintf(f, "`%s`\n\n", r.ClassifyTiming)
	}

	if len(r.Latency) > 0 {
		fmt.Fprintln(f, "### API latency")
		fmt.Fprintf(f, "\nProbe duration %s, %d concurrent workers.\n\n",
			r.ProbeDuration.Round(time.Second), r.ProbeWorkers)
		fmt.Fprintln(f, "| path | n | err | p50 | p95 | p99 | max |")
		fmt.Fprintln(f, "|---|---:|---:|---:|---:|---:|---:|")
		for _, lat := range r.Latency {
			fmt.Fprintf(f, "| `%s` | %d | %d | %s | %s | %s | %s |\n",
				lat.Path, lat.N, lat.Errors,
				ms(lat.P50), ms(lat.P95), ms(lat.P99), ms(lat.Max))
		}
		fmt.Fprintln(f)
	}

	return nil
}

type jsonResult struct {
	Name           string        `json:"name"`
	TargetRef      string        `json:"target_ref"`
	Trial          int           `json:"trial"`
	Binary         string        `json:"binary"`
	Daemon         string        `json:"daemon"`
	GoVersion      string        `json:"go_version"`
	HostOS         string        `json:"host_os"`
	Timestamp      string        `json:"timestamp"`
	TipReached     bool          `json:"tip_reached"`
	TimeToTipMS    int64         `json:"time_to_tip_ms"`
	ReadyPattern   string        `json:"ready_pattern"`
	ReadyReached   bool          `json:"ready_reached"`
	TimeToReadyMS  int64         `json:"time_to_ready_ms"`
	DBBytes        int64         `json:"db_bytes"`
	ProbeDuration  string        `json:"probe_duration"`
	ProbeWorkers   int           `json:"probe_workers"`
	ProbePaths     []string      `json:"probe_paths"`
	Latency        []jsonLatency `json:"latency"`
	ClassifyTiming string        `json:"classify_timing"`
	LogPath        string        `json:"log_path"`
}

type jsonLatency struct {
	Path   string `json:"path"`
	N      int    `json:"n"`
	Errors int    `json:"errors"`
	P50MS  int64  `json:"p50_ms"`
	P95MS  int64  `json:"p95_ms"`
	P99MS  int64  `json:"p99_ms"`
	MaxMS  int64  `json:"max_ms"`
}

func appendJSONReport(path string, r Result) error {
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600) // #nosec G304 -- report path is operator-selected output.
	if err != nil {
		return err
	}
	defer f.Close()

	targetRef := r.TargetRef
	if targetRef == "" {
		targetRef = r.Name
	}
	row := jsonResult{
		Name:           r.Name,
		TargetRef:      targetRef,
		Trial:          r.Trial,
		Binary:         r.Binary,
		Daemon:         r.Daemon,
		GoVersion:      r.GoVersion,
		HostOS:         r.HostOS,
		Timestamp:      r.Timestamp,
		TipReached:     r.TipReached,
		TimeToTipMS:    r.TimeToTip.Milliseconds(),
		ReadyPattern:   r.ReadyPattern,
		ReadyReached:   r.ReadyReached,
		TimeToReadyMS:  r.TimeToReady.Milliseconds(),
		DBBytes:        r.DBBytes,
		ProbeDuration:  r.ProbeDuration.String(),
		ProbeWorkers:   r.ProbeWorkers,
		ProbePaths:     append([]string(nil), r.ProbePaths...),
		ClassifyTiming: r.ClassifyTiming,
		LogPath:        r.LogPath,
	}
	row.Latency = make([]jsonLatency, 0, len(r.Latency))
	for _, lat := range r.Latency {
		row.Latency = append(row.Latency, jsonLatency{
			Path:   lat.Path,
			N:      lat.N,
			Errors: lat.Errors,
			P50MS:  lat.P50.Milliseconds(),
			P95MS:  lat.P95.Milliseconds(),
			P99MS:  lat.P99.Milliseconds(),
			MaxMS:  lat.Max.Milliseconds(),
		})
	}

	enc := json.NewEncoder(f)
	return enc.Encode(row)
}

// humanBytes formats a byte count into a compact human-readable
// string. Stops at GiB — bench DBs in the multi-TB range would be
// a red flag worth surfacing.
func humanBytes(n int64) string {
	const (
		KB = 1 << 10
		MB = 1 << 20
		GB = 1 << 30
	)
	switch {
	case n >= GB:
		return fmt.Sprintf("%.2f GiB (%d bytes)", float64(n)/GB, n)
	case n >= MB:
		return fmt.Sprintf("%.1f MiB (%d bytes)", float64(n)/MB, n)
	case n >= KB:
		return fmt.Sprintf("%.1f KiB (%d bytes)", float64(n)/KB, n)
	default:
		return fmt.Sprintf("%d bytes", n)
	}
}

// ms formats a duration in millisecond precision for table rows.
// Sub-ms values report as "<1ms" rather than 0 so the operator
// doesn't mistake fast-path cache hits for failed measurements.
func ms(d time.Duration) string {
	if d == 0 {
		return "—"
	}
	if d < time.Millisecond {
		return "<1 ms"
	}
	return d.Round(time.Millisecond).String()
}
